name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "23/31 3,10,17 * * MON-SAT"
#sleep $[RANDOM % 1500]
#echo "{name}={value}" >> $GITHUB_OUTPUT
#echo "::set-output name=should_skip::$should_skip"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: should skip
        id: check_skip
        run: |
          should_skip=$([ $((RANDOM % 2)) -eq 1 ] && echo true || echo false)
          echo "should_skip=$should_skip" >> $GITHUB_OUTPUT
      
      - name: Auto green
        if: steps.check_skip.outputs.should_skip != 'true'
        run: |
          git config --local user.email "2015210899@bupt.cn"
          git config --local user.name "huainan1m"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
