name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "39/13 2,10,19,23 * * MON-SAT"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          sleep $((RANDOM % 1000))
          git config --local user.email "2015210899@bupt.cn"
          git config --local user.name "huainan1m"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
